// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Catalog.SDK.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CatalogItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The availableStock property</summary>
        public int? AvailableStock { get; set; }
        /// <summary>The catalogBrand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Catalog.SDK.Models.CatalogBrand? CatalogBrand { get; set; }
#nullable restore
#else
        public global::Catalog.SDK.Models.CatalogBrand CatalogBrand { get; set; }
#endif
        /// <summary>The catalogBrandId property</summary>
        public int? CatalogBrandId { get; set; }
        /// <summary>The catalogType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Catalog.SDK.Models.CatalogType? CatalogType { get; set; }
#nullable restore
#else
        public global::Catalog.SDK.Models.CatalogType CatalogType { get; set; }
#endif
        /// <summary>The catalogTypeId property</summary>
        public int? CatalogTypeId { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The maxStockThreshold property</summary>
        public int? MaxStockThreshold { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The onReorder property</summary>
        public bool? OnReorder { get; set; }
        /// <summary>The pictureFileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PictureFileName { get; set; }
#nullable restore
#else
        public string PictureFileName { get; set; }
#endif
        /// <summary>The price property</summary>
        public double? Price { get; set; }
        /// <summary>The restockThreshold property</summary>
        public int? RestockThreshold { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Catalog.SDK.Models.CatalogItem"/> and sets the default values.
        /// </summary>
        public CatalogItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Catalog.SDK.Models.CatalogItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Catalog.SDK.Models.CatalogItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Catalog.SDK.Models.CatalogItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availableStock", n => { AvailableStock = n.GetIntValue(); } },
                { "catalogBrand", n => { CatalogBrand = n.GetObjectValue<global::Catalog.SDK.Models.CatalogBrand>(global::Catalog.SDK.Models.CatalogBrand.CreateFromDiscriminatorValue); } },
                { "catalogBrandId", n => { CatalogBrandId = n.GetIntValue(); } },
                { "catalogType", n => { CatalogType = n.GetObjectValue<global::Catalog.SDK.Models.CatalogType>(global::Catalog.SDK.Models.CatalogType.CreateFromDiscriminatorValue); } },
                { "catalogTypeId", n => { CatalogTypeId = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "maxStockThreshold", n => { MaxStockThreshold = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "onReorder", n => { OnReorder = n.GetBoolValue(); } },
                { "pictureFileName", n => { PictureFileName = n.GetStringValue(); } },
                { "price", n => { Price = n.GetDoubleValue(); } },
                { "restockThreshold", n => { RestockThreshold = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("availableStock", AvailableStock);
            writer.WriteObjectValue<global::Catalog.SDK.Models.CatalogBrand>("catalogBrand", CatalogBrand);
            writer.WriteIntValue("catalogBrandId", CatalogBrandId);
            writer.WriteObjectValue<global::Catalog.SDK.Models.CatalogType>("catalogType", CatalogType);
            writer.WriteIntValue("catalogTypeId", CatalogTypeId);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("maxStockThreshold", MaxStockThreshold);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("onReorder", OnReorder);
            writer.WriteStringValue("pictureFileName", PictureFileName);
            writer.WriteDoubleValue("price", Price);
            writer.WriteIntValue("restockThreshold", RestockThreshold);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
