// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Catalog.Items.Item.Pic;
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Api.Catalog.Items.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\catalog\items\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The pic property</summary>
        public global::ApiSdk.Api.Catalog.Items.Item.Pic.PicRequestBuilder Pic
        {
            get => new global::ApiSdk.Api.Catalog.Items.Item.Pic.PicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items/{id}?api-version={api%2Dversion}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items/{id}?api-version={api%2Dversion}", rawUrl)
        {
        }
        /// <summary>
        /// Delete the specified catalog item
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get an item from the catalog
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.CatalogItem"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.CatalogItem?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.CatalogItem> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.CatalogItem>(requestInfo, global::ApiSdk.Models.CatalogItem.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create or replace a catalog item
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiSdk.Models.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PutAsync(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PutAsync(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::ApiSdk.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete the specified catalog item
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Get an item from the catalog
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create or replace a catalog item
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Delete the specified catalog item
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsDeleteApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::ApiSdk.Api.Catalog.Items.Item.DeleteApiVersionQueryParameterType? ApiVersionAsDeleteApiVersionQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderDeleteQueryParameters>
        {
        }
        /// <summary>
        /// Get an item from the catalog
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsItemRequestBuilderGetQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsGetApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::ApiSdk.Api.Catalog.Items.Item.GetApiVersionQueryParameterType? ApiVersionAsGetApiVersionQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Create or replace a catalog item
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsItemRequestBuilderPutQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsPutApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::ApiSdk.Api.Catalog.Items.Item.PutApiVersionQueryParameterType? ApiVersionAsPutApiVersionQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsItemRequestBuilderPutRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder.ItemsItemRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
