// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CatalogItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The availableStock property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? AvailableStock { get; set; }
#nullable restore
#else
        public UntypedNode AvailableStock { get; set; }
#endif
        /// <summary>The catalogBrand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand? CatalogBrand { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand CatalogBrand { get; set; }
#endif
        /// <summary>The catalogBrandId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CatalogBrandId { get; set; }
#nullable restore
#else
        public UntypedNode CatalogBrandId { get; set; }
#endif
        /// <summary>The catalogType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType? CatalogType { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType CatalogType { get; set; }
#endif
        /// <summary>The catalogTypeId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CatalogTypeId { get; set; }
#nullable restore
#else
        public UntypedNode CatalogTypeId { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Id { get; set; }
#nullable restore
#else
        public UntypedNode Id { get; set; }
#endif
        /// <summary>The maxStockThreshold property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? MaxStockThreshold { get; set; }
#nullable restore
#else
        public UntypedNode MaxStockThreshold { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The onReorder property</summary>
        public bool? OnReorder { get; set; }
        /// <summary>The pictureFileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PictureFileName { get; set; }
#nullable restore
#else
        public string PictureFileName { get; set; }
#endif
        /// <summary>The price property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Price { get; set; }
#nullable restore
#else
        public UntypedNode Price { get; set; }
#endif
        /// <summary>The restockThreshold property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RestockThreshold { get; set; }
#nullable restore
#else
        public UntypedNode RestockThreshold { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.CatalogItem"/> and sets the default values.
        /// </summary>
        public CatalogItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.CatalogItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.CatalogItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.CatalogItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availableStock", n => { AvailableStock = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "catalogBrand", n => { CatalogBrand = n.GetObjectValue<global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand>(global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand.CreateFromDiscriminatorValue); } },
                { "catalogBrandId", n => { CatalogBrandId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "catalogType", n => { CatalogType = n.GetObjectValue<global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType>(global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType.CreateFromDiscriminatorValue); } },
                { "catalogTypeId", n => { CatalogTypeId = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "maxStockThreshold", n => { MaxStockThreshold = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "onReorder", n => { OnReorder = n.GetBoolValue(); } },
                { "pictureFileName", n => { PictureFileName = n.GetStringValue(); } },
                { "price", n => { Price = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "restockThreshold", n => { RestockThreshold = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("availableStock", AvailableStock);
            writer.WriteObjectValue<global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand>("catalogBrand", CatalogBrand);
            writer.WriteObjectValue<UntypedNode>("catalogBrandId", CatalogBrandId);
            writer.WriteObjectValue<global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType>("catalogType", CatalogType);
            writer.WriteObjectValue<UntypedNode>("catalogTypeId", CatalogTypeId);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<UntypedNode>("id", Id);
            writer.WriteObjectValue<UntypedNode>("maxStockThreshold", MaxStockThreshold);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("onReorder", OnReorder);
            writer.WriteStringValue("pictureFileName", PictureFileName);
            writer.WriteObjectValue<UntypedNode>("price", Price);
            writer.WriteObjectValue<UntypedNode>("restockThreshold", RestockThreshold);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.CatalogBrand"/>, <see cref="global::ApiSdk.Models.CatalogItem_catalogBrandMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CatalogItem_catalogBrand : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.CatalogBrand"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.CatalogBrand? CatalogBrand { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.CatalogBrand CatalogBrand { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.CatalogItem_catalogBrandMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.CatalogItem_catalogBrandMember1? CatalogItemCatalogBrandMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.CatalogItem_catalogBrandMember1 CatalogItemCatalogBrandMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::ApiSdk.Models.CatalogItem.CatalogItem_catalogBrand();
                if("CatalogBrand".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CatalogBrand = new global::ApiSdk.Models.CatalogBrand();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CatalogItemCatalogBrandMember1 = new global::ApiSdk.Models.CatalogItem_catalogBrandMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CatalogBrand != null)
                {
                    return CatalogBrand.GetFieldDeserializers();
                }
                else if(CatalogItemCatalogBrandMember1 != null)
                {
                    return CatalogItemCatalogBrandMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CatalogBrand != null)
                {
                    writer.WriteObjectValue<global::ApiSdk.Models.CatalogBrand>(null, CatalogBrand);
                }
                else if(CatalogItemCatalogBrandMember1 != null)
                {
                    writer.WriteObjectValue<global::ApiSdk.Models.CatalogItem_catalogBrandMember1>(null, CatalogItemCatalogBrandMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::ApiSdk.Models.CatalogItem_catalogTypeMember1"/>, <see cref="global::ApiSdk.Models.CatalogType"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CatalogItem_catalogType : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.CatalogItem_catalogTypeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.CatalogItem_catalogTypeMember1? CatalogItemCatalogTypeMember1 { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.CatalogItem_catalogTypeMember1 CatalogItemCatalogTypeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::ApiSdk.Models.CatalogType"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::ApiSdk.Models.CatalogType? CatalogType { get; set; }
#nullable restore
#else
            public global::ApiSdk.Models.CatalogType CatalogType { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::ApiSdk.Models.CatalogItem.CatalogItem_catalogType();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CatalogItemCatalogTypeMember1 = new global::ApiSdk.Models.CatalogItem_catalogTypeMember1();
                }
                else if("CatalogType".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CatalogType = new global::ApiSdk.Models.CatalogType();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CatalogItemCatalogTypeMember1 != null)
                {
                    return CatalogItemCatalogTypeMember1.GetFieldDeserializers();
                }
                else if(CatalogType != null)
                {
                    return CatalogType.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CatalogItemCatalogTypeMember1 != null)
                {
                    writer.WriteObjectValue<global::ApiSdk.Models.CatalogItem_catalogTypeMember1>(null, CatalogItemCatalogTypeMember1);
                }
                else if(CatalogType != null)
                {
                    writer.WriteObjectValue<global::ApiSdk.Models.CatalogType>(null, CatalogType);
                }
            }
        }
    }
}
#pragma warning restore CS0618
