// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Catalog.SDK.Api.Catalog.Items.Item.Pic
{
    /// <summary>
    /// Builds and executes requests for operations under \api\catalog\items\{id}\pic
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items/{id}/pic?api-version={api%2Dversion}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items/{id}/pic?api-version={api%2Dversion}", rawUrl)
        {
        }
        /// <summary>
        /// Get the picture for a catalog item
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder.PicRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder.PicRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the picture for a catalog item
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder.PicRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder.PicRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/octet-stream, image/png, image/gif, image/jpeg, image/bmp, image/tiff, image/wmf, image/jp2, image/svg+xml, image/webp");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get the picture for a catalog item
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PicRequestBuilderGetQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsGetApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::Catalog.SDK.Api.Catalog.Items.Item.Pic.GetApiVersionQueryParameterType? ApiVersionAsGetApiVersionQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PicRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Catalog.SDK.Api.Catalog.Items.Item.Pic.PicRequestBuilder.PicRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
