// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Api.Catalog.Catalogtypes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\catalog\catalogtypes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CatalogtypesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogtypesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/catalogtypes?api-version={api%2Dversion}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogtypesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/catalogtypes?api-version={api%2Dversion}", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of the types of catalog items
        /// </summary>
        /// <returns>A List&lt;global::ApiSdk.Models.CatalogType&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::ApiSdk.Models.CatalogType>?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder.CatalogtypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::ApiSdk.Models.CatalogType>> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder.CatalogtypesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::ApiSdk.Models.CatalogType>(requestInfo, global::ApiSdk.Models.CatalogType.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Get a list of the types of catalog items
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder.CatalogtypesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder.CatalogtypesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a list of the types of catalog items
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CatalogtypesRequestBuilderGetQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsGetApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::ApiSdk.Api.Catalog.Catalogtypes.GetApiVersionQueryParameterType? ApiVersionAsGetApiVersionQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CatalogtypesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder.CatalogtypesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
