// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Catalog.Items.By;
using ApiSdk.Api.Catalog.Items.Item;
using ApiSdk.Api.Catalog.Items.Withsemanticrelevance;
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Api.Catalog.Items
{
    /// <summary>
    /// Builds and executes requests for operations under \api\catalog\items
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItemsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The by property</summary>
        public global::ApiSdk.Api.Catalog.Items.By.ByRequestBuilder By
        {
            get => new global::ApiSdk.Api.Catalog.Items.By.ByRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The withsemanticrelevance property</summary>
        public global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder Withsemanticrelevance
        {
            get => new global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ApiSdk.api.catalog.items.item collection</summary>
        /// <param name="position">The catalog item id</param>
        /// <returns>A <see cref="global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder"/></returns>
        public global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ApiSdk.api.catalog.items.item collection</summary>
        /// <param name="position">The catalog item id</param>
        /// <returns>A <see cref="global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::ApiSdk.Api.Catalog.Items.Item.ItemsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items?api-version={api%2Dversion}{&PageIndex*,PageSize*,brand*,name*,type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ItemsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items?api-version={api%2Dversion}{&PageIndex*,PageSize*,brand*,name*,type*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a paginated list of items in the catalog.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.PaginatedItemsOfCatalogItem"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.PaginatedItemsOfCatalogItem?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.PaginatedItemsOfCatalogItem> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.PaginatedItemsOfCatalogItem>(requestInfo, global::ApiSdk.Models.PaginatedItemsOfCatalogItem.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new item in the catalog
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a paginated list of items in the catalog.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new item in the catalog
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ApiSdk.Models.CatalogItem body, Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/api/catalog/items?api-version={api%2Dversion}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/problem+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a paginated list of items in the catalog.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsRequestBuilderGetQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsGetApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::ApiSdk.Api.Catalog.Items.GetApiVersionQueryParameterType? ApiVersionAsGetApiVersionQueryParameterType { get; set; }
            /// <summary>The brand of items to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("brand")]
            public string? Brand { get; set; }
#nullable restore
#else
            [QueryParameter("brand")]
            public string Brand { get; set; }
#endif
            /// <summary>The name of the item to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>The index of the page of results to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? PageIndex { get; set; }
#nullable restore
#else
            public string PageIndex { get; set; }
#endif
            /// <summary>Number of items to return in a single page of results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? PageSize { get; set; }
#nullable restore
#else
            public string PageSize { get; set; }
#endif
            /// <summary>The type of items to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("type")]
            public string? Type { get; set; }
#nullable restore
#else
            [QueryParameter("type")]
            public string Type { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Create a new item in the catalog
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsRequestBuilderPostQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsPostApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::ApiSdk.Api.Catalog.Items.PostApiVersionQueryParameterType? ApiVersionAsPostApiVersionQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ItemsRequestBuilderPostRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder.ItemsRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
