// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Catalog.SDK.Api.Catalog.Items
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostApiVersionQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "2.0")]
        #pragma warning disable CS1591
        TwoZero,
        #pragma warning restore CS1591
    }
}
