// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Api.Catalog.Catalogbrands;
using ApiSdk.Api.Catalog.Catalogtypes;
using ApiSdk.Api.Catalog.Items;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Api.Catalog
{
    /// <summary>
    /// Builds and executes requests for operations under \api\catalog
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CatalogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The catalogbrands property</summary>
        public global::ApiSdk.Api.Catalog.Catalogbrands.CatalogbrandsRequestBuilder Catalogbrands
        {
            get => new global::ApiSdk.Api.Catalog.Catalogbrands.CatalogbrandsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The catalogtypes property</summary>
        public global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder Catalogtypes
        {
            get => new global::ApiSdk.Api.Catalog.Catalogtypes.CatalogtypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder Items
        {
            get => new global::ApiSdk.Api.Catalog.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.CatalogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.CatalogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CatalogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
