// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Api.Catalog.Items.Withsemanticrelevance
{
    /// <summary>
    /// Builds and executes requests for operations under \api\catalog\items\withsemanticrelevance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithsemanticrelevanceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithsemanticrelevanceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items/withsemanticrelevance?api-version={api%2Dversion}&text={text}{&PageIndex*,PageSize*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithsemanticrelevanceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/catalog/items/withsemanticrelevance?api-version={api%2Dversion}&text={text}{&PageIndex*,PageSize*}", rawUrl)
        {
        }
        /// <summary>
        /// Search the catalog for items related to the specified text
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.PaginatedItemsOfCatalogItem"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiSdk.Models.ProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.PaginatedItemsOfCatalogItem?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder.WithsemanticrelevanceRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.PaginatedItemsOfCatalogItem> GetAsync(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder.WithsemanticrelevanceRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiSdk.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.PaginatedItemsOfCatalogItem>(requestInfo, global::ApiSdk.Models.PaginatedItemsOfCatalogItem.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Search the catalog for items related to the specified text
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder.WithsemanticrelevanceRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder.WithsemanticrelevanceRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Search the catalog for items related to the specified text
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithsemanticrelevanceRequestBuilderGetQueryParameters 
        {
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [Obsolete("This property is deprecated, use ApiVersionAsGetApiVersionQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("api%2Dversion")]
            public string? ApiVersion { get; set; }
#nullable restore
#else
            [QueryParameter("api%2Dversion")]
            public string ApiVersion { get; set; }
#endif
            /// <summary>The API version, in the format &apos;major.minor&apos;.</summary>
            [QueryParameter("api%2Dversion")]
            public global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.GetApiVersionQueryParameterType? ApiVersionAsGetApiVersionQueryParameterType { get; set; }
            /// <summary>The index of the page of results to return</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? PageIndex { get; set; }
#nullable restore
#else
            public string PageIndex { get; set; }
#endif
            /// <summary>Number of items to return in a single page of results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? PageSize { get; set; }
#nullable restore
#else
            public string PageSize { get; set; }
#endif
            /// <summary>The text string to use when search for related items in the catalog</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("text")]
            public string? Text { get; set; }
#nullable restore
#else
            [QueryParameter("text")]
            public string Text { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithsemanticrelevanceRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.Api.Catalog.Items.Withsemanticrelevance.WithsemanticrelevanceRequestBuilder.WithsemanticrelevanceRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
